# Generated by Django 3.1.1 on 2020-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namecard_tbl',
            options={'ordering': ('group', 'name'), 'verbose_name': 'namecard', 'verbose_name_plural': 'namecards'},
        ),
        migrations.AlterField(
            model_name='namecard_tbl',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE'),
        ),
        migrations.AlterField(
            model_name='namecard_tbl',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='namecard_tbl',
            name='modify_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='MODIFY DATE'),
        ),
    ]
