# Generated by Django 3.1.1 on 2020-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('number', models.CharField(help_text='학번 입력', max_length=100, unique=True, verbose_name='NUMBER')),
                ('major', models.CharField(blank=True, help_text='전공 입력', max_length=100, verbose_name='MAJOR')),
                ('tel', models.CharField(max_length=50, verbose_name='MOBILE')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='EMAIL')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ('-modify_dt',),
            },
        ),
    ]
