# Generated by Django 3.1.1 on 2020-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(help_text='전공 입력', max_length=100, verbose_name='MAJOR'),
        ),
    ]
